### ISSUE TITLE
Need a subee cli installation guide

### ISSUE THREAD

**Issue by potsbo** [wantedly/subee#27]
## WHY

When I was checking [the example](https://github.com/wantedly/subee/tree/master/_examples/your-first-cloudpubsub-app), I found that subee cli seems really handy but I couldn't tell how to install it.

## WHAT

I found `go get github.com/wantedly/subee/cmd/subee` is the best way available. Isn't it better to document this or any other way to perform the installation?
@izumin5210

**Comment by potsbo** [comment]
I also found out subee panics in the command below.
I don't know this happens only in my env.
```
$ subee g subscriber event -p ./pkg/model -m Event
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x12c5134]

goroutine 1 [running]:
github.com/wantedly/subee/cmd/subee/internal/generator.(*subscriberGeneratorImpl).Generate(0xc0001743a0, 0x1406ba0, 0xc00001c0d8, 0xc0001a8000, 0xc000010010, 0xc0000efd40)
        /Users/shimpei/.go/src/github.com/wantedly/subee/cmd/subee/internal/generator/subscriber.go:65 +0x1604
github.com/wantedly/subee/cmd/subee/cmd.newGenerateSubscriberCmd.func1(0xc0001a6500, 0xc0001ac050, 0x1, 0x5, 0x0, 0x0)
        /Users/shimpei/.go/src/github.com/wantedly/subee/cmd/subee/cmd/generate.go:58 +0x269
github.com/spf13/cobra.(*Command).execute(0xc0001a6500, 0xc0001ac000, 0x5, 0x5, 0xc0001a6500, 0xc0001ac000)
        /Users/shimpei/.go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a6000, 0x105f33d, 0x1327240, 0xc00016c810)
        /Users/shimpei/.go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/shimpei/.go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.run(0x1397fc3, 0x20)
        /Users/shimpei/.go/src/github.com/wantedly/subee/cmd/subee/main.go:18 +0x28
main.main()
        /Users/shimpei/.go/src/github.com/wantedly/subee/cmd/subee/main.go:11 +0x26
```

**Comment by potsbo** [comment]
Exactly the same happens when I try with [the latest release binary](https://github.com/wantedly/subee/releases/tag/v0.4.0).
```
subee g subscriber event -p ./pkg/model -m Event
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x12c4514]

goroutine 1 [running]:
github.com/wantedly/subee/cmd/subee/internal/generator.(*subscriberGeneratorImpl).Generate(0xc00000c540, 0x1405d80, 0xc0000a2000, 0xc00018a000, 0xc000096000, 0xc0000dbd40)
        /home/circleci/project/cmd/subee/internal/generator/subscriber.go:65 +0x1604
github.com/wantedly/subee/cmd/subee/cmd.newGenerateSubscriberCmd.func1(0xc000188500, 0xc000190050, 0x1, 0x5, 0x0, 0x0)
        /home/circleci/project/cmd/subee/cmd/generate.go:58 +0x269
github.com/spf13/cobra.(*Command).execute(0xc000188500, 0xc000190000, 0x5, 0x5, 0xc000188500, 0xc000190000)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000188000, 0x105e7ad, 0x1326620, 0xc000052a80)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.run(0x1397385, 0x20)
        /home/circleci/project/cmd/subee/main.go:18 +0x28
main.main()
        /home/circleci/project/cmd/subee/main.go:11 +0x26
```

**Comment by potsbo** [comment]
It seems the panic is because of my fault. But I think we should note that the doc can be improved.

**Comment by izumin5210** [comment]
We store prebuilt binaries for each platform in the [Releases](https://github.com/wantedly/subee/releases) page. And we also provide [Homebrew Tap](https://github.com/wantedly/homebrew-tap) repository to distribute our tools.

So I think the best way to install subee CLI is to download prebuilt one:


- Download from GitHub Releases
    - ```console
      curl -L https://github.com/wantedly/subee/releases/download/v0.4.0/subee_linux_amd64.tar.gz | tar xzf -
      cp subee_linux_amd64/subee /usr/local/bin/
      rm -rf subee_linux_amd64
      ```
- with Homebrew
    - `brew install wantedly/tap/grapi`

**Comment by potsbo** [comment]
Thanks. Maybe `brew install wantedly/tap/subee`?
Let me add the installations to README.
